#%RAML 1.0
title: People
version: v1
baseUri: http://api.people.com

documentation:
  - title: Home
    content: !include documentation/home.markdown
  - title: Credits
    content: !include documentation/about.markdown

mediaType: application/json


types:
  People:
    type: object
    properties:
      id: number
      firstName: string
      lastName: string
/people:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "people": [
                  {
                    "id":123232,
                    "firstName":"Fernando",
                    "lastName":"Zendron"
                  },
                  {
                    "id":3874759,
                    "firstName":"Enzo",
                    "lastName":"Zendron"
                  },
                  {
                    "id":290847,
                    "firstName":"Maria",
                    "lastName":"Valdeene"
                  }
                ]
              }
            displayName: People
